---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: komga
  annotations:
    nfs.io/storage-path: "data01/komga"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mangas
  annotations:
    nfs.io/storage-path: "data02/media/mangas"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
