kind: Deployment
apiVersion: apps/v1
metadata:
  name: komga
  labels:
    app: komga
    part-of: komga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
      part-of: komga
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: komga
        part-of: komga
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - name: komga
        image: gotson/komga:0.153.1
        ports:
        - name: komga
          containerPort: 8080
        env:
        - name: KOMGA_LIBRARIES_SCAN_CRON
          value: "0 0 * * * ?"
        - name: KOMGA_REMEMBERME_KEY 
          value: "random"
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:+UseContainerSupport -XX:+UnlockExperimentalVMOptions -XX:MaxRAM=4g"
        - name: KOMGA_FILE_HASHING
          value: "false"
        - name: KOMGA_OAUTH2_ACCOUNT_CREATION
          value: "true"
        volumeMounts:
        - name: komga
          mountPath: /config
        - name: mangas
          mountPath: /mangas
        readinessProbe:
          httpGet:
            path: /
            port: komga
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: komga
          initialDelaySeconds: 25
          periodSeconds: 20
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 4Gi
      volumes:
      - name: komga
        persistentVolumeClaim:
          claimName: komga
      - name: mangas
        persistentVolumeClaim:
          claimName: mangas
